name: CI - Build and Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-cloud-app .

    - name: Run and test
      run: |
        docker run -d -p 5000:5000 --name test-app my-cloud-app
        sleep 3
        curl http://localhost:5000
        curl http://localhost:5000/health
